const std = @import("std");

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit();
    const alloc = gpa.allocator();

    var args = try std.process.argsWithAllocator(alloc);
    defer args.deinit();

    _ = args.next(); // skip exe name
    const pages_dir = args.next() orelse {
        std.debug.print("Usage: build_router <pages_dir> <out_file>\n", .{});
        return;
    };
    const out_file = args.next() orelse {
        std.debug.print("Usage: build_router <pages_dir> <out_file>\n", .{});
        return;
    };

    std.debug.print("[RouterGen] Scanning pages dir: {s}\n", .{pages_dir});

    var routes: std.ArrayListUnmanaged([]const u8) = .empty;
    defer {
        for (routes.items) |r| alloc.free(r);
        routes.deinit(alloc);
    }

    // Walk the directory
    var dir = std.fs.cwd().openDir(pages_dir, .{ .iterate = true }) catch |err| {
        if (err == error.FileNotFound) {
            std.debug.print("[RouterGen] Warning: Pages dir not found, generating empty router.\n", .{});
            try generateEmptyRouter(alloc, out_file);
            return;
        }
        return err;
    };
    defer dir.close();

    var walker = try dir.walk(alloc);
    defer walker.deinit();

    while (try walker.next()) |entry| {
        if (entry.kind == .file and std.mem.endsWith(u8, entry.basename, ".zig")) {
            // Path relative to pages directory, e.g., "blog/post.zig"
             const route_path = try alloc.dupe(u8, entry.path[0..entry.path.len - 4]);
             try routes.append(alloc, route_path);
        }
    }

    try generateRouterFile(alloc, routes.items, out_file);
    std.debug.print("[RouterGen] Generated {s} with {d} routes\n", .{out_file, routes.items.len});
}

fn generateEmptyRouter(alloc: std.mem.Allocator, out_file: []const u8) !void {
    const file = try std.fs.cwd().createFile(out_file, .{});
    defer file.close();
    
    const content = 
        \\const std = @import("std");
        \\
        \\// Auto-generated by build_router.zig
        \\pub fn initRoutes(server: anytype) !void {
        \\    _ = server;
        \\}
        \\
    ;
    try file.writeAll(content);
    _ = alloc;
}

fn generateRouterFile(alloc: std.mem.Allocator, routes: [][]const u8, out_file: []const u8) !void {
    const file = try std.fs.cwd().createFile(out_file, .{});
    defer file.close();
    try file.writeAll("const std = @import(\"std\");\n\n");

    for (routes, 0..) |relative_path, i| {
        const import_line = try std.fmt.allocPrint(alloc, "const comp_{d} = @import(\"pages_components/{s}.zig\");\n", .{ i, relative_path });
        defer alloc.free(import_line);
        try file.writeAll(import_line);
    }

    try file.writeAll(
        \\
        \\// Auto-generated file-system router
        \\pub fn initRoutes(server: anytype) !void {
        \\
    );

    for (routes) |relative_path| {
        // Convert "blog/post.psx" to "/blog/post"
        var normalized: std.ArrayListUnmanaged(u8) = .empty;
        defer normalized.deinit(alloc);

        try normalized.append(alloc, '/');

        const without_ext = relative_path;
        
        var iter = std.mem.splitScalar(u8, without_ext, std.fs.path.sep);
        var first = true;
        while (iter.next()) |segment| {
            if (!first) try normalized.append(alloc, '/');
            first = false;

            // Handle index.psx -> /
            if (std.mem.eql(u8, segment, "index") and without_ext.len == 5) {
                // Keep it just "/"
                break;
            }

            // Handle [slug] -> {slug}
            if (std.mem.startsWith(u8, segment, "[") and std.mem.endsWith(u8, segment, "]")) {
                try normalized.append(alloc, '{');
                try normalized.appendSlice(alloc, segment[1..segment.len - 1]);
                try normalized.append(alloc, '}');
            } else {
                try normalized.appendSlice(alloc, segment);
            }
        }

        // e.g. path = "/blog/{slug}", handler_key = "page:blog/[slug].zx"
        const final_route = normalized.items;
        
        // Output handler registration
        const line = try std.fmt.allocPrint(alloc,
            "    try server.page(\"{s}\", \"page:{s}\", .ssr);\n",
            .{ final_route, relative_path }
        );
        defer alloc.free(line);
        try file.writeAll(line);
    }

    try file.writeAll("}\n\n");

    try file.writeAll(
        \\pub fn renderPage(alloc: std.mem.Allocator, writer: anytype, handler_key: []const u8) !bool {
        \\    _ = alloc;
        \\
    );

    for (routes, 0..) |relative_path, i| {
        const block = try std.fmt.allocPrint(alloc, 
            \\    if (std.mem.eql(u8, handler_key, "page:{s}")) {{
            \\        try comp_{d}.render(alloc, writer);
            \\        return true;
            \\    }}
            \\
        , .{ relative_path, i });
        defer alloc.free(block);
        try file.writeAll(block);
    }

    try file.writeAll("    return false;\n}\n");
}
